# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
# app/config/services.yml
parameters:
#    parameter_name: value

services:
  app.rule_manager:
    class: AppBundle\Service\RuleManager
