# app/config/services.yml
parameters:

services:
  app.rule_manager:
    class: AppBundle\Service\RuleManager

  app.rule_manager.is_numeric:
    class: AppBundle\RuleManager\IsNumericRule
    tags:
      - { name: rule_manager.rule }

  app.rule_manager.greater_than:
    class: AppBundle\RuleManager\GreaterThanRule
    tags:
      - { name: rule_manager.rule }

  app.rule_manager.less_then:
    class: AppBundle\RuleManager\LessThanRule
    tags:
      - { name: rule_manager.rule }
